# Site settings
title: Your blog title
header-img: img/home-bg.png
email: shmuel.markel@gmail.com
copyright_name: Shmuli Markel
description: > # this means to ignore newlines until "baseurl:"
  A short subtitle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: shmulim
github_username:  shmulim
learn_profile: Shmuli
email_username: shmuel.markel@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
